version: '3.1'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-container
    #restar: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      #altenticacao com senha obrigatoria
      POSTGRES_HOST_AUTH_METHOD: 'md5'
    ports:
      - "5432:5432"
    volumes:
      - ./volume:/var/lib/postgresql/data